spring:
  #指定服务名
  application:
    name: message-service
  server:
    port: 8080
  #redis配置
  redis:
    #Redis服务器地址
    host: 192.168.1.10
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最小空闲连接
        min-idle: 2
    #连接超时时间（毫秒）
    timeout: 5000
    
#  rabbitMQ配置
  rabbitmq:
    host: 192.168.1.10
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
      username: root
      password: cl1991625
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
#  原文链接：https://blog.csdn.net/zhuzhezhuzhe1/article/details/80561449
#阿里云短信服务，为了动态配置这些值,不至于硬编码
aliyun:
  sms:
    accessKeyId:
    accessKeySecret:
    template_code: 模板编码
    sign_name: 签名

